### ISSUE TITLE
Plugin `EDMC-Screenshot` does not load, only for Flatpak version

### ISSUE THREAD

**Issue by joebetsill** [flathub/io.edcd.EDMarketConnector#2]
I am not sure if this is the proper place for issues, or if I should put this over at the main EDMC github-- I'm starting here and we'll see how it goes. :)

The plugin `EDMC-Screenshot` does not seem to load at all with the flatpak version of EDMC. The other plugins I use seem to load fine. When I run EDMC via proton, this plugin works as expected, so I am assuming that the issue lies with something to do with the flatpak version. (As opposed to the main EDMC code, or the plugin itself.)

I would pull logs but I have no idea where they're going-- not to any `tmp` folder I could find. If you know where I should look, I'll gladly provide them.

I am on SteamOS beta.

The other plugins I have that _did_ load are:
* EDMC-Cannon
* EDSM-RSE
* SpanshRouter

Let me know what else I can do to help, or if I should have made this in another repo.

I've been waiting for this to be made into a flatpak; thanks a ton for the work you put in!

**Comment by Athanasius** [comment]
I suspect this is because EDMC-Screenshot relies on Pillow/PIL for the image processing and *that* has architecture-specific libraries.  It currently ships only for 32-bit Windows.

AIUI SteamOS is Linux+WINE-based, so such a plugin just isn't going to work unless you fiddle around getting the correct version of PIL in place.  You could contact [the EDMC-Screenshot](https://github.com/NoFoolLikeOne/EDMC-Screenshot/) maintainer to see if they want to expand support to Linux.

And, yes, currently EDMC is still a 32-bit application, so requires 32-bit libraries in such situations.  We're working on changing to 64-bit.

**Comment by NoFoolLikeOne** [comment]
ISTR Someone has a linux version of that plugin.

**Comment by joebetsill** [comment]
I see. Well, if this isn't an issue with the flapak version, I'm going to mark it closed. I guess I'll keep running it with proton/steam for now. Thanks everyone!
